-- MySQL Script generated by MySQL Workbench
-- Чт. 28 янв. 2016 06:04:16
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sample_server
-- -----------------------------------------------------
-- Схема для размещения данных сервера.

-- -----------------------------------------------------
-- Schema sample_server
--
-- Схема для размещения данных сервера.
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sample_server` DEFAULT CHARACTER SET utf8 ;
USE `sample_server` ;

-- -----------------------------------------------------
-- Table `sample_server`.`account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sample_server`.`account` (
  `id` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'Уникальный ид аккаунта.',
  `name` VARCHAR(255) NOT NULL COMMENT 'Имя пользователя аккаунта.',
  `password` VARCHAR(45) NOT NULL COMMENT 'Пароль от аккаунта.',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COMMENT = 'Таблица для размещения аккаунтов пользователей.';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
